### ISSUE TITLE
Respi-wheat link not working

### ISSUE THREAD

**Issue by opieters** [openalea-incubator/cn-wheat#3]
The link provided to the download of `respi-wheat` no longer works. There is a repo that covers the same [on Github](https://github.com/openalea-incubator/respi-wheat). So the link should be updated to that location. 

Furthermore, I think that the installation procedure could be more user-friendly. Adding the package (and `respi-wheat`) to [PyPI](https://pypi.org/) whould make it a lot easier to get started, since Anaconda en Pip can automatically install all necessary dependencies.

**Comment by rbarillot** [comment]
Hi Olivier !
I'm sorry you get in trouble.
You're right the links are not up to date because we are currently working to a new package structure (see [WheatFspm](https://github.com/openalea-incubator/WheatFspm)). This work is still in progress but the idea is to install all submodels from a single repo. 
thanks for the feedback,
